# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "7"

dist: trusty

# https://docs.travis-ci.com/user/installing-dependencies/

install:
  - npm install

script:
  - npm test
  - npm run-script pdf -- --source="./" --output="./docs/" --clean
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs
  on:
    branch: master
